# Print newline at the start of the prompt
add_newline = true

# replace > with ->
[character]
symbol = "âœ"
error_symbol = "âœ—"
use_symbol_for_status = true


[cmd_duration]
min_time = 500
show_milliseconds = true


[directory]
truncate_length = 5


[battery]
full_symbol = "â˜» "
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ”‹"
disabled = false

[[battery.display]]
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"


[memory_usage]
show_percentage = false
show_swap = true
threshold = -1
symbol = "ğŸ”€ "
style = "bold dimmed green"
disabled = false


[git_status]
show_sync_count = true
staged_count.enabled = true


[kubernetes]
disabled = false


[time]
disabled = false


[username]
show_always = true


[package]
disabled = true

