# required starship 0.45.0 or newer

add_newline = true
command_timeout = 1500

[character]
success_symbol = "[‚ùØ](bold green)"
error_symbol = "[‚úó](bold red)"
vicmd_symbol = "[V](bold green)"


[cmd_duration]
min_time = 500
show_milliseconds = true


[directory]
truncation_length = 3
truncation_symbol = "‚Ä¶/"


[battery]
full_symbol = "Û±ä£ "
charging_symbol = "Û∞ÇÑ "
discharging_symbol = "Û±ä¢ "
disabled = false

[[battery.display]]
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"


[memory_usage]
threshold = -1
format = "$symbol[${ram}( | ${swap})]($style) "
symbol = "üß† "
style = "bold dimmed green"
disabled = false


[docker_context]
disabled = false


[time]
disabled = false


[username]
show_always = true


[package]
disabled = true


[status]
disabled = false

